/* Copyright 2019-2021,2024 NXP
 * 
 * SPDX-License-Identifier: Apache-2.0
 * 
 * 
 */

#ifndef NXP_IOT_AGENT_VERSION_INFO_H_INCLUDED
#define NXP_IOT_AGENT_VERSION_INFO_H_INCLUDED


/* clang-format off */
#define NXP_IOT_AGENT_PROD_NAME          "nxp_iot_agent"
#define NXP_IOT_AGENT_VER_STRING_NUM     "v06.00.02_20241219"
#define NXP_IOT_AGENT_PROD_NAME_VER_FULL "nxp_iot_agent_v06.00.02_20241219"
#define NXP_IOT_AGENT_VER_MAJOR          (6u)
#define NXP_IOT_AGENT_VER_MINOR          (0u)
#define NXP_IOT_AGENT_VER_DEV            (2u)

/* v06.00 = 60000u */
#define NXP_IOT_AGENT_VER_MAJOR_MINOR ( 0 \
    | (NXP_IOT_AGENT_VER_MAJOR * 10000u)    \
    | (NXP_IOT_AGENT_VER_MINOR))

/* v06.00.02 = 600000002ULL */
#define NXP_IOT_AGENT_VER_MAJOR_MINOR_DEV ( 0 \
    | (NXP_IOT_AGENT_VER_MAJOR * 10000*10000u)    \
    | (NXP_IOT_AGENT_VER_MINOR * 10000u)    \
    | (NXP_IOT_AGENT_VER_DEV))

/* clang-format on */


/* Version Information:
 * Generated by:
 *     version_info.py (v2019.01.17_00)
 * 
 * Do not edit this file. Update:
 *     ./version_info.txt instead.
 * 
 * 
 * prod_name = "nxp_iot_agent"
 * 
 * prod_desc = "EdgeLock 2GO agent"
 * 
 * lang_c_prefix = prod_name.upper()
 * 
 * lang_namespace = ""
 * 
 * v_major  = "06"
 * 
 * v_minor  = "00"
 * 
 * v_dev    = "02"
 * 
 * v_meta   = ""
 * 
 * maturity = "B"
 * 
 */

#endif /* NXP_IOT_AGENT_VERSION_INFO_H_INCLUDED */
