/*
 *  Copyright The Mbed TLS Contributors
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"); you may
 *  not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/* Copyright 2021,2024 NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
/* GENERATED FILE. DO NOT EDIT!! */
/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!! */

/* clang-format off */

#ifndef __MBEDTLS_USER_CONFIG_H__
#define __MBEDTLS_USER_CONFIG_H__

#if defined(SSS_USE_FTR_FILE)
#include "fsl_sss_ftr.h"
#else
#include "fsl_sss_ftr_default.h"
#endif

/* Generated by sss_x86_mbedtls_config.py */

#ifndef MBEDTLS_CMAC_C
    #define MBEDTLS_CMAC_C
#endif // MBEDTLS_CMAC_C

#if SSS_HAVE_MBEDTLS_ALT_PSA
#ifndef MBEDTLS_NIST_KW_C
    #define MBEDTLS_NIST_KW_C
#endif // MBEDTLS_NIST_KW_C
#endif //  SSS_HAVE_MBEDTLS_ALT_PSA

#if SSS_HAVE_MBEDTLS_ALT_PSA
#ifndef MBEDTLS_PSA_CRYPTO_DRIVERS
    #define MBEDTLS_PSA_CRYPTO_DRIVERS
#endif // MBEDTLS_PSA_CRYPTO_DRIVERS
#endif //  SSS_HAVE_MBEDTLS_ALT_PSA

#if SSS_HAVE_MBEDTLS_ALT_PSA
#ifndef MBEDTLS_USE_PSA_CRYPTO
    #define MBEDTLS_USE_PSA_CRYPTO
#endif // MBEDTLS_USE_PSA_CRYPTO
#endif //  SSS_HAVE_MBEDTLS_ALT_PSA


#if defined(MBEDTLS_SELF_TEST)
    #undef MBEDTLS_SELF_TEST
#endif // MBEDTLS_SELF_TEST

#include <fsl_sss_types.h>

#ifndef MBEDTLS_PLATFORM_MEMORY
    #define MBEDTLS_PLATFORM_MEMORY
#endif // MBEDTLS_PLATFORM_MEMORY

#if defined(MBEDTLS_PLATFORM_STD_CALLOC)
    #undef MBEDTLS_PLATFORM_STD_CALLOC
#endif // MBEDTLS_PLATFORM_STD_CALLOC

#if defined(MBEDTLS_PLATFORM_STD_FREE)
    #undef MBEDTLS_PLATFORM_STD_FREE
#endif // MBEDTLS_PLATFORM_STD_FREE

#if defined(MBEDTLS_PLATFORM_CALLOC_MACRO)
    #undef MBEDTLS_PLATFORM_CALLOC_MACRO
#endif // MBEDTLS_PLATFORM_CALLOC_MACRO

#if defined(MBEDTLS_PLATFORM_FREE_MACRO)
    #undef MBEDTLS_PLATFORM_FREE_MACRO
#endif // MBEDTLS_PLATFORM_FREE_MACRO


#define MBEDTLS_PLATFORM_CALLOC_MACRO SSS_CALLOC
#define MBEDTLS_PLATFORM_FREE_MACRO SSS_FREE

#if defined(FD_SETSIZE)
    #undef FD_SETSIZE
#endif // FD_SETSIZE
#define FD_SETSIZE 1024

#endif /* __MBEDTLS_USER_CONFIG_H__ */
